version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "dependabot(actions): "
    reviewers:
      # - '@tokamak-network/layer2-core'
      - '@xxeonge'
    target-branch: "OR-1861-Automatic-update-of-action-version-using-dependabot" #"main"
